### ISSUE TITLE
SimPar variables not defined in the readme

### ISSUE THREAD

**Issue by catarinawor** [Pacific-salmon-assess/samSim#13]
**biasCor**, **adjustForecast** and **agePpnConst** are not defined in the readme.

**Comment by CamFreshwater** [comment]
Good catch! I'll dredge my faulty memory and try to get definitions in this week.

**Comment by catarinawor** [comment]
Ha! This was more for @carrieholt and @krHolt . I'm documenting samSim for the LRP work. It might be possible that those variables are only relevant for that branch.

**Comment by CamFreshwater** [comment]
Whew relief because a quick search didn't show anything too familiar for two of those three! 

However **adjustForecast** (at least in my version) is a scalar applied to the parameter describing forecast error. I.e. it's used to generate MPs that have the same forecast model, but differ in forecast performance. Just in case this has been changed though probably best for Carrie or Kendra to chime in!

**Comment by catarinawor** [comment]
Added all three variables.
